# Generated by Django 5.0.6 on 2024-11-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salons', '0001_initial'),
        ('services', '__first__'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='barbers',
            field=models.ManyToManyField(blank=True, related_name='salon_list', to='users.barber'),
        ),
        migrations.AddField(
            model_name='salon',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='salons_list', to='services.salonservices'),
        ),
    ]
