# Generated by Django 5.0.6 on 2024-11-06 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghour',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.barber'),
        ),
    ]
