# Generated by Django 5.0.6 on 2024-11-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_appointment_barber_alter_appointment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='working_hours',
            field=models.ManyToManyField(blank=True, related_name='barbers', to='users.workinghour'),
        ),
    ]
