# Generated by Django 5.0.6 on 2024-11-08 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_barber_working_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barber',
            old_name='working_hours',
            new_name='workinghours',
        ),
    ]
